;;; -*- Mode: lisp; Syntax: ansi-common-lisp; Base: 10; Package: xml-query-data-model; -*-

(in-package :xml-query-data-model)
(setq xml-query-data-model:*namespace*
      (xml-query-data-model:defnamespace "http://rhizomik.net/ontologies/2006/01/copyrightonto.owl#"
                                         (:use)
                                         (:nicknames)
                                         (:export
                                          "Access"
                                          "Action"
                                          "Adapt"
                                          "AdaptationRight"
                                          "Agree"
                                          "Aim"
                                          "Ambient"
                                          "Attend"
                                          "Attribute"
                                          "AttributionRight"
                                          "Broadcast"
                                          "BroadcastedCommunication"
                                          "BroadcastersRights"
                                          "BroadcastingRight"
                                          "BroadcastMedium"
                                          "Cite"
                                          "Collective"
                                          "Communicate"
                                          "Communication"
                                          "CommunicationMedium"
                                          "CommunicationRight"
                                          "Copy"
                                          "Copyright"
                                          "CounterOffer"
                                          "Creation"
                                          "CreationConcept"
                                          "CreationObject"
                                          "CreationProcess"
                                          "Derive"
                                          "DisclosureRight"
                                          "Distribute"
                                          "DistributionContract"
                                          "DistributionRight"
                                          "EconomicRights"
                                          "EconomicTransfer"
                                          "EditionContract"
                                          "EducationRight"
                                          "Fixation"
                                          "FixationRight"
                                          "Give"
                                          "ImportationRight"
                                          "Improvisation"
                                          "Improvise"
                                          "InformationRight"
                                          "Instance"
                                          "IntegrityRight"
                                          "InteractiveCommunication"
                                          "InteractiveMedium"
                                          "IPRAgreement"
                                          "LegalPerson"
                                          "Lend"
                                          "LiveCommunicate"
                                          "LiveCommunication"
                                          "MakeAvailable"
                                          "MakingAvailableRight"
                                          "Manifest"
                                          "Manifestation"
                                          "MoralRights"
                                          "MotionPicture"
                                          "MotionPictureRight"
                                          "NaturalPerson"
                                          "Offer"
                                          "OfficialActRight"
                                          "ParodyRight"
                                          "Perform"
                                          "Performance"
                                          "PerformersRights"
                                          "Person"
                                          "PrivateCopyRight"
                                          "Process"
                                          "ProducersRights"
                                          "ProductionContract"
                                          "PublicPerformanceRight"
                                          "PublicPlace"
                                          "QuotationRight"
                                          "Record"
                                          "RecordedCommunication"
                                          "RecordingCommunicate"
                                          "RelatedRights"
                                          "Rent"
                                          "RentalRight"
                                          "ReproductionRight"
                                          "Sell"
                                          "SoundRecording"
                                          "SoundRecordingRight"
                                          "Spatial"
                                          "Temporal"
                                          "TemporaryReproductionRight"
                                          "Transfer"
                                          "TransformationRight"
                                          "Translate"
                                          "TranslationRight"
                                          "Tune"
                                          "Use"
                                          "UsersRights"
                                          "Verb"
                                          "Withdraw"
                                          "WithdrawalRight"
                                          "Work")
                                         (:documentation nil)))

(let ((xml-query-data-model::p
       (or (find-package "http://rhizomik.net/ontologies/2006/01/copyrightonto.owl#")
           (make-package "http://rhizomik.net/ontologies/2006/01/copyrightonto.owl#"
                         :use
                         nil
                         :nicknames
                         'nil))))
  (dolist (xml-query-data-model::s
           '("Access" "Action" "Adapt" "AdaptationRight" "Agree" "Aim"
             "Ambient" "Attend" "Attribute" "AttributionRight" "Broadcast"
             "BroadcastedCommunication" "BroadcastersRights"
             "BroadcastingRight" "BroadcastMedium" "Cite" "Collective"
             "Communicate" "Communication" "CommunicationMedium"
             "CommunicationRight" "Copy" "Copyright" "CounterOffer" "Creation"
             "CreationConcept" "CreationObject" "CreationProcess" "Derive"
             "DisclosureRight" "Distribute" "DistributionContract"
             "DistributionRight" "EconomicRights" "EconomicTransfer"
             "EditionContract" "EducationRight" "Fixation" "FixationRight"
             "Give" "ImportationRight" "Improvisation" "Improvise"
             "InformationRight" "Instance" "IntegrityRight"
             "InteractiveCommunication" "InteractiveMedium" "IPRAgreement"
             "LegalPerson" "Lend" "LiveCommunicate" "LiveCommunication"
             "MakeAvailable" "MakingAvailableRight" "Manifest" "Manifestation"
             "MoralRights" "MotionPicture" "MotionPictureRight" "NaturalPerson"
             "Offer" "OfficialActRight" "ParodyRight" "Perform" "Performance"
             "PerformersRights" "Person" "PrivateCopyRight" "Process"
             "ProducersRights" "ProductionContract" "PublicPerformanceRight"
             "PublicPlace" "QuotationRight" "Record" "RecordedCommunication"
             "RecordingCommunicate" "RelatedRights" "Rent" "RentalRight"
             "ReproductionRight" "Sell" "SoundRecording" "SoundRecordingRight"
             "Spatial" "Temporal" "TemporaryReproductionRight" "Transfer"
             "TransformationRight" "Translate" "TranslationRight" "Tune" "Use"
             "UsersRights" "Verb" "Withdraw" "WithdrawalRight" "Work"))
    (export (intern xml-query-data-model::s xml-query-data-model::p)
            xml-query-data-model::p)))

;;; (xqdm:find-namespace "http://rhizomik.net/ontologies/2006/01/copyrightonto.owl#" :if-does-not-exist :load)
