;;; -*- Mode: lisp; Syntax: ansi-common-lisp; Base: 10; Package: xml-query-data-model; -*-

(in-package :xml-query-data-model)
(setq xml-query-data-model:*namespace*
      (xml-query-data-model:defnamespace "http://sweet.jpl.nasa.gov/ontology/property.owl#"
                                         (:use)
                                         (:nicknames)
                                         (:export
                                          "AbsoluteVorticity"
                                          "Absorptance"
                                          "Acceleration"
                                          "AcousticRelatedQuantity"
                                          "Active"
                                          "AerodynamicsRelatedQuantity"
                                          "Albedo"
                                          "Alkalinity"
                                          "Altitude"
                                          "AmbientNoise"
                                          "Amplitude"
                                          "AngstromExponent"
                                          "Anisotropy"
                                          "Area"
                                          "AtmosphericPressure"
                                          "BarometricAltitude"
                                          "BarortopicStreamfunction"
                                          "Bathymetry"
                                          "BenthicIndex"
                                          "BinaryProperty"
                                          "Bioavailability"
                                          "BiologicalQuantity"
                                          "Biomass"
                                          "BlockingIndex"
                                          "BowenRatio"
                                          "Brightness"
                                          "BrightnessTemperature"
                                          "BruntVaisalaFrequency"
                                          "BulkDensity"
                                          "Capacity"
                                          "Ceiling"
                                          "Characteristics"
                                          "ChemicalQuantity"
                                          "CirculationIndex"
                                          "Classification"
                                          "Closed"
                                          "CloudForcing"
                                          "CoefficientOfExpansion"
                                          "Color"
                                          "Comminution"
                                          "CommonSenseClimateIndex"
                                          "Composition"
                                          "CompositionRelatedQuantity"
                                          "Conductivity"
                                          "Consistence"
                                          "Convergence"
                                          "CoriolisParameter"
                                          "Count"
                                          "CropMoistureIndex"
                                          "CrossSection"
                                          "DegreeDay"
                                          "DeicedTemperature"
                                          "Density"
                                          "Depth"
                                          "Description"
                                          "DewPoint"
                                          "DewPointDepression"
                                          "DewPointTemperature"
                                          "DifferentialPressure"
                                          "Dissipation"
                                          "DissolvedConcentration"
                                          "Distance"
                                          "Distribution"
                                          "Divergence"
                                          "Dormant"
                                          "DragCoefficient"
                                          "DryBulbTemperature"
                                          "DynamicViscosity"
                                          "EathquakeMagnitude"
                                          "ElectricField"
                                          "ElectricityRelatedQuantity"
                                          "ElectricPotential"
                                          "ElectromagneticFieldRelatedQuantity"
                                          "ElectromagneticRadiationRelatedQuantity"
                                          "Elevation"
                                          "Emissivity"
                                          "Energy"
                                          "EnergyRelatedQuantity"
                                          "Enthalpy"
                                          "EquivalentTemperature"
                                          "EquivalentThickness"
                                          "ErtelPotentialVorticity"
                                          "ExchangeCapacity"
                                          "ExnerFunction"
                                          "Exotic"
                                          "ExtensiveQuantity"
                                          "Extent"
                                          "Extinct"
                                          "ExtinctionCoefficient"
                                          "F10.7"
                                          "Fertility"
                                          "Fetch"
                                          "FieldCapacity"
                                          "FieldStrength"
                                          "FineStructure"
                                          "FireWeatherIndex"
                                          "FluidProperty"
                                          "Force"
                                          "ForestFireDangerIndex"
                                          "Frequency"
                                          "GeoMagneticField"
                                          "GeomagneticIndex"
                                          "Geopotential"
                                          "GeopotentialHeight"
                                          "GeotechnicalProperty"
                                          "GravitationalRelatedQuantity"
                                          "GravityField"
                                          "GravityForce"
                                          "Habitat"
                                          "HallConductivity"
                                          "Health"
                                          "Heat"
                                          "HeatCapacity"
                                          "HeatEnergy"
                                          "Height"
                                          "Humidity"
                                          "HumidityIndex"
                                          "HydraulicConductivity"
                                          "HydroPattern"
                                          "HydrostaticPressure"
                                          "Impedance"
                                          "Index"
                                          "Inductance"
                                          "Insolation"
                                          "IntensiveQuantity"
                                          "Irradiance"
                                          "KaplanSstIndex"
                                          "KinematicViscosity"
                                          "KineticEnergy"
                                          "Kp"
                                          "LatentHeat"
                                          "LeafAreaIndex"
                                          "Length"
                                          "Level"
                                          "LinearExtent"
                                          "LiquidWaterEquivalent"
                                          "MagneticField"
                                          "MagneticInduction"
                                          "MagnetismRelatedQuantity"
                                          "Mass"
                                          "MassConcentration"
                                          "MassConcentrationRelatedQuantity"
                                          "MassContent"
                                          "MassRelatedQuantity"
                                          "MediumProperty"
                                          "MeridionalOvertuningStreamfunction"
                                          "Microstructure"
                                          "Moisture"
                                          "MoleFraction"
                                          "Momentum"
                                          "MotionRelatedQuantity"
                                          "Noise"
                                          "NorthAtlanticOscillationIndex"
                                          "NorthPacificOscillationIndex"
                                          "Omega"
                                          "Open"
                                          "OpticalDepth"
                                          "OpticalThickness"
                                          "OscillationRelatedQuantity"
                                          "OxygenDemand"
                                          "PartialPressure"
                                          "Pattern"
                                          "PedersenConductivity"
                                          "pH"
                                          "Phase"
                                          "PhotolysisRate"
                                          "PhysicalQuantity"
                                          "Pigment"
                                          "Plasticity"
                                          "Population"
                                          "Porosity"
                                          "PotentialDensity"
                                          "PotentialEnergy"
                                          "PotentialTemperature"
                                          "PotentialVorticity"
                                          "Precipitable"
                                          "Pressure"
                                          "PressureRelatedQuantity"
                                          "PressureThickness"
                                          "Productivity"
                                          "PseudoEquivalentPotentialTemperature"
                                          "PseudoEquivalentTemperature"
                                          "QualitativeMeasure"
                                          "Quality"
                                          "Quantity"
                                          "Radiance"
                                          "RadiantEnergy"
                                          "Radiation-MediumInteractionRelatedQuantity"
                                          "RadiationBalanceRelatedQuantity"
                                          "RadiativeForcing"
                                          "Radioactive"
                                          "Radioactivity"
                                          "Rainfall"
                                          "Reflectance"
                                          "Reflectivity"
                                          "RelativeHumidity"
                                          "RelativeVorticity"
                                          "Roughness"
                                          "Salinity"
                                          "SaturationDeficit"
                                          "ScaleHeight"
                                          "SeaState"
                                          "SecchiDepth"
                                          "SensibleHeat"
                                          "Shear"
                                          "SigmaT"
                                          "SignificantHeight"
                                          "Size"
                                          "SolarRadiation"
                                          "SolidMaterialProperty"
                                          "SpatialExtent"
                                          "SpatialExtentRelatedQuantity"
                                          "SpatialRange"
                                          "SpecificGravitationalPotentialEnergy"
                                          "SpecificHeat"
                                          "SpecificHumidity"
                                          "SpecificPotentialEnergy"
                                          "Spectrum"
                                          "Speed"
                                          "Stability"
                                          "StageHeight"
                                          "StandardizedPrecipitationIndex"
                                          "State"
                                          "StaticPressure"
                                          "StaticTemperature"
                                          "Streamfunction"
                                          "Stress"
                                          "Structure"
                                          "SubstanceConcentration"
                                          "SubstanceConcentrationRelatedQuantity"
                                          "SubstanceContent"
                                          "SurfaceMoistureIndex"
                                          "Temperature"
                                          "TemperatureRelatedQuantity"
                                          "Texture"
                                          "ThermalConductivity"
                                          "ThermalDiffusivity"
                                          "Thickness"
                                          "Time"
                                          "TimeRelatedQuantity"
                                          "Topography"
                                          "TotalElectronContent"
                                          "TotalPressure"
                                          "TotalTemperature"
                                          "Transmittance"
                                          "Turbidity"
                                          "Type"
                                          "Value"
                                          "Velocity"
                                          "VelocityFieldRelatedProperty"
                                          "VelocityPotential"
                                          "VerticalExtent"
                                          "VirtualTemperature"
                                          "Visibility"
                                          "Volume"
                                          "Vorticity"
                                          "WaterConcentration"
                                          "WaterHoldingCapacity"
                                          "Wavelength"
                                          "WetBulbTemperature"
                                          "WindChill"
                                          "WindIndex"
                                          "Yield")
                                         (:documentation nil)))

(let ((xml-query-data-model::p
       (or (find-package "http://sweet.jpl.nasa.gov/ontology/property.owl#")
           (make-package "http://sweet.jpl.nasa.gov/ontology/property.owl#"
                         :use
                         nil
                         :nicknames
                         'nil))))
  (dolist (xml-query-data-model::s
           '("AbsoluteVorticity" "Absorptance" "Acceleration"
             "AcousticRelatedQuantity" "Active" "AerodynamicsRelatedQuantity"
             "Albedo" "Alkalinity" "Altitude" "AmbientNoise" "Amplitude"
             "AngstromExponent" "Anisotropy" "Area" "AtmosphericPressure"
             "BarometricAltitude" "BarortopicStreamfunction" "Bathymetry"
             "BenthicIndex" "BinaryProperty" "Bioavailability"
             "BiologicalQuantity" "Biomass" "BlockingIndex" "BowenRatio"
             "Brightness" "BrightnessTemperature" "BruntVaisalaFrequency"
             "BulkDensity" "Capacity" "Ceiling" "Characteristics"
             "ChemicalQuantity" "CirculationIndex" "Classification" "Closed"
             "CloudForcing" "CoefficientOfExpansion" "Color" "Comminution"
             "CommonSenseClimateIndex" "Composition"
             "CompositionRelatedQuantity" "Conductivity" "Consistence"
             "Convergence" "CoriolisParameter" "Count" "CropMoistureIndex"
             "CrossSection" "DegreeDay" "DeicedTemperature" "Density" "Depth"
             "Description" "DewPoint" "DewPointDepression"
             "DewPointTemperature" "DifferentialPressure" "Dissipation"
             "DissolvedConcentration" "Distance" "Distribution" "Divergence"
             "Dormant" "DragCoefficient" "DryBulbTemperature"
             "DynamicViscosity" "EathquakeMagnitude" "ElectricField"
             "ElectricityRelatedQuantity" "ElectricPotential"
             "ElectromagneticFieldRelatedQuantity"
             "ElectromagneticRadiationRelatedQuantity" "Elevation" "Emissivity"
             "Energy" "EnergyRelatedQuantity" "Enthalpy"
             "EquivalentTemperature" "EquivalentThickness"
             "ErtelPotentialVorticity" "ExchangeCapacity" "ExnerFunction"
             "Exotic" "ExtensiveQuantity" "Extent" "Extinct"
             "ExtinctionCoefficient" "F10.7" "Fertility" "Fetch"
             "FieldCapacity" "FieldStrength" "FineStructure" "FireWeatherIndex"
             "FluidProperty" "Force" "ForestFireDangerIndex" "Frequency"
             "GeoMagneticField" "GeomagneticIndex" "Geopotential"
             "GeopotentialHeight" "GeotechnicalProperty"
             "GravitationalRelatedQuantity" "GravityField" "GravityForce"
             "Habitat" "HallConductivity" "Health" "Heat" "HeatCapacity"
             "HeatEnergy" "Height" "Humidity" "HumidityIndex"
             "HydraulicConductivity" "HydroPattern" "HydrostaticPressure"
             "Impedance" "Index" "Inductance" "Insolation" "IntensiveQuantity"
             "Irradiance" "KaplanSstIndex" "KinematicViscosity" "KineticEnergy"
             "Kp" "LatentHeat" "LeafAreaIndex" "Length" "Level" "LinearExtent"
             "LiquidWaterEquivalent" "MagneticField" "MagneticInduction"
             "MagnetismRelatedQuantity" "Mass" "MassConcentration"
             "MassConcentrationRelatedQuantity" "MassContent"
             "MassRelatedQuantity" "MediumProperty"
             "MeridionalOvertuningStreamfunction" "Microstructure" "Moisture"
             "MoleFraction" "Momentum" "MotionRelatedQuantity" "Noise"
             "NorthAtlanticOscillationIndex" "NorthPacificOscillationIndex"
             "Omega" "Open" "OpticalDepth" "OpticalThickness"
             "OscillationRelatedQuantity" "OxygenDemand" "PartialPressure"
             "Pattern" "PedersenConductivity" "pH" "Phase" "PhotolysisRate"
             "PhysicalQuantity" "Pigment" "Plasticity" "Population" "Porosity"
             "PotentialDensity" "PotentialEnergy" "PotentialTemperature"
             "PotentialVorticity" "Precipitable" "Pressure"
             "PressureRelatedQuantity" "PressureThickness" "Productivity"
             "PseudoEquivalentPotentialTemperature"
             "PseudoEquivalentTemperature" "QualitativeMeasure" "Quality"
             "Quantity" "Radiance" "RadiantEnergy"
             "Radiation-MediumInteractionRelatedQuantity"
             "RadiationBalanceRelatedQuantity" "RadiativeForcing" "Radioactive"
             "Radioactivity" "Rainfall" "Reflectance" "Reflectivity"
             "RelativeHumidity" "RelativeVorticity" "Roughness" "Salinity"
             "SaturationDeficit" "ScaleHeight" "SeaState" "SecchiDepth"
             "SensibleHeat" "Shear" "SigmaT" "SignificantHeight" "Size"
             "SolarRadiation" "SolidMaterialProperty" "SpatialExtent"
             "SpatialExtentRelatedQuantity" "SpatialRange"
             "SpecificGravitationalPotentialEnergy" "SpecificHeat"
             "SpecificHumidity" "SpecificPotentialEnergy" "Spectrum" "Speed"
             "Stability" "StageHeight" "StandardizedPrecipitationIndex" "State"
             "StaticPressure" "StaticTemperature" "Streamfunction" "Stress"
             "Structure" "SubstanceConcentration"
             "SubstanceConcentrationRelatedQuantity" "SubstanceContent"
             "SurfaceMoistureIndex" "Temperature" "TemperatureRelatedQuantity"
             "Texture" "ThermalConductivity" "ThermalDiffusivity" "Thickness"
             "Time" "TimeRelatedQuantity" "Topography" "TotalElectronContent"
             "TotalPressure" "TotalTemperature" "Transmittance" "Turbidity"
             "Type" "Value" "Velocity" "VelocityFieldRelatedProperty"
             "VelocityPotential" "VerticalExtent" "VirtualTemperature"
             "Visibility" "Volume" "Vorticity" "WaterConcentration"
             "WaterHoldingCapacity" "Wavelength" "WetBulbTemperature"
             "WindChill" "WindIndex" "Yield"))
    (export (intern xml-query-data-model::s xml-query-data-model::p)
            xml-query-data-model::p)))

;;; (xqdm:find-namespace "http://sweet.jpl.nasa.gov/ontology/property.owl#" :if-does-not-exist :load)
