;;; -*- Mode: lisp; Syntax: ansi-common-lisp; Base: 10; Package: xml-query-data-model; -*-

(in-package :xml-query-data-model)
(setq xml-query-data-model:*namespace*
      (xml-query-data-model:defnamespace "http://sweet.jpl.nasa.gov/sweet/earthrealm.owl#"
                                         (:use)
                                         (:nicknames)
                                         (:export
                                          "AbyssalHill"
                                          "AbyssalPlain"
                                          "ActiveLayer"
                                          "Aeoliean"
                                          "AgriculturalLands"
                                          "AlpineClimateZone"
                                          "AphoticZone"
                                          "Aquifer"
                                          "ArcticClimateZone"
                                          "Asthenosphere"
                                          "Atmosphere"
                                          "AtmosphereLayer"
                                          "AtmosphereLayerBoundary"
                                          "BarrierIsland"
                                          "Beach"
                                          "Bedrock"
                                          "Benthic"
                                          "Benthos"
                                          "BenticEcosystem"
                                          "Biosphere"
                                          "BodyOfGround"
                                          "BodyOfIce"
                                          "BodyOfSeaIce"
                                          "BodyOfWater"
                                          "BorealForest"
                                          "BoundaryLayer"
                                          "Cave"
                                          "CaveEcosystem"
                                          "Cirque"
                                          "ClimateZoneType"
                                          "CoastalRegion"
                                          "Continent"
                                          "ContinentalMargin"
                                          "CoralReef"
                                          "Core"
                                          "CoreLayer"
                                          "CostalLandform"
                                          "Creek"
                                          "Crust"
                                          "CrustLayer"
                                          "Cryosphere"
                                          "CryosphereLayer"
                                          "DeepOcean"
                                          "Delta"
                                          "DemersalEcosystem"
                                          "DepthHoarLayer"
                                          "Desert_Ecosystem"
                                          "DesertClimateZone"
                                          "DryLandRegion"
                                          "Dune"
                                          "EarthRealm"
                                          "EcosystemType"
                                          "EolianLandform"
                                          "EstuarineWetland"
                                          "Estuary"
                                          "Exosphere"
                                          "F-Region"
                                          "Farmland"
                                          "FastIce"
                                          "Felsic"
                                          "fiord"
                                          "Fjord"
                                          "FluvialLandform"
                                          "Forest_Ecosystem"
                                          "FractureZone"
                                          "FreshwaterLake"
                                          "GeomorphologicalRegionType"
                                          "Geosphere"
                                          "GeosphereLayer"
                                          "GlacialLandform"
                                          "Glacier"
                                          "GlobalPlanetaryLayers"
                                          "Grassland"
                                          "GroundSurfaceLayer"
                                          "GroundWaterObjectBoundary"
                                          "Halocline"
                                          "Hydrosphere"
                                          "HydrosphereLayer"
                                          "HydrothermalVents"
                                          "Iceberg"
                                          "IceCore"
                                          "IceFloe"
                                          "IceLayer"
                                          "IceSheet"
                                          "Inlet"
                                          "IntertidalZone"
                                          "InversionLayer"
                                          "Ionosphere"
                                          "Island"
                                          "IslandArc"
                                          "Isobar"
                                          "Isopycnal"
                                          "KarstLandform"
                                          "LacustrineWetland"
                                          "Lagoon"
                                          "Lake"
                                          "LakeLayer"
                                          "Land"
                                          "Land_WaterBoundary_2D"
                                          "LandIce"
                                          "LandIceLayer"
                                          "LandRegion"
                                          "LandSurface"
                                          "LandSurfaceLayer"
                                          "LandWaterObject"
                                          "LandwaterRegion"
                                          "LandWaterSurface"
                                          "LandwaterSurfaceLayer"
                                          "Leads"
                                          "Lithosphere"
                                          "LithosphereLayer"
                                          "Litter"
                                          "Littoral"
                                          "LowerAtmosphere"
                                          "LowerMantle"
                                          "Mafic"
                                          "Magnetosphere"
                                          "MangroveForest"
                                          "Mantle"
                                          "MantleLayer"
                                          "MarineEcosystem"
                                          "MarineWetland"
                                          "Marsh"
                                          "MediterraneanClimateZone"
                                          "Mesopause"
                                          "Mesosphere"
                                          "MiddleAtmosphere"
                                          "MixedLayer"
                                          "Moho"
                                          "MontaneForest"
                                          "Mountain"
                                          "Nearshore"
                                          "Ocean"
                                          "OceanCrustLayer"
                                          "OceanLayer"
                                          "OceanRegion"
                                          "OceanRidge"
                                          "PackIce"
                                          "PalustrineWetland"
                                          "Peatland"
                                          "PelagicEcosystem"
                                          "PeriglacialLandform"
                                          "Permafrost"
                                          "PermafrostZone"
                                          "PhoticZone"
                                          "Plain"
                                          "PlanetaryStructure"
                                          "PlanetarySurface"
                                          "PlanetarySurfaceLayer"
                                          "PlanetEarth"
                                          "Plateau"
                                          "Polynya"
                                          "Pond"
                                          "Pycnocline"
                                          "RegionProperty"
                                          "Ridge"
                                          "RiftValley"
                                          "RiparianWetland"
                                          "River"
                                          "Rock_body"
                                          "RockGlacier"
                                          "RockyCoast"
                                          "SalineLake"
                                          "Savanna"
                                          "Sea"
                                          "SeaFloor"
                                          "SeaFloorGroundLayer"
                                          "SeaFloorRegion"
                                          "SeaFloorWaterLayer"
                                          "SeaIce"
                                          "SeaIceLayer"
                                          "Seamount"
                                          "SeaSurface"
                                          "SeaSurfaceLayer"
                                          "SedimentaryStructure"
                                          "SedimentLayer"
                                          "Shoal"
                                          "Shoreline"
                                          "SkinLayer"
                                          "Sky"
                                          "SnowField"
                                          "SnowLayer"
                                          "SoilLayer"
                                          "SolidEarth"
                                          "Spring"
                                          "Stratopause"
                                          "Stratosphere"
                                          "Stream"
                                          "SubmarineCanyon"
                                          "SubsurfaceWater"
                                          "SubtropicalClimateZone"
                                          "SurfaceRegion"
                                          "SurfaceWater"
                                          "Swamp"
                                          "Talik"
                                          "TectonicLandform"
                                          "TemperateClimateZone"
                                          "TerrestrialEcosystem"
                                          "TerrrestrialWetland"
                                          "Thermocline"
                                          "Thermosphere"
                                          "TopographicalRegion"
                                          "Trench"
                                          "TropicalClimateZone"
                                          "Tropopause"
                                          "Troposphere"
                                          "TroposphereLayer"
                                          "Tundra_Ecosystem"
                                          "UndergroundWater"
                                          "UpperAir"
                                          "UpperAtmosphere"
                                          "UpperMantle_flowing"
                                          "UpperMantle_rigid"
                                          "UrbanLand"
                                          "Volcano"
                                          "WaterChannel"
                                          "Watershed"
                                          "WaterSurface"
                                          "WaterSurfaceLayer"
                                          "WaterTable"
                                          "Wetland"
                                          "WetlandRegion")
                                         (:documentation nil)))

(let ((xml-query-data-model::p
       (or (find-package "http://sweet.jpl.nasa.gov/sweet/earthrealm.owl#")
           (make-package "http://sweet.jpl.nasa.gov/sweet/earthrealm.owl#"
                         :use
                         nil
                         :nicknames
                         'nil))))
  (dolist (xml-query-data-model::s
           '("AbyssalHill" "AbyssalPlain" "ActiveLayer" "Aeoliean"
             "AgriculturalLands" "AlpineClimateZone" "AphoticZone" "Aquifer"
             "ArcticClimateZone" "Asthenosphere" "Atmosphere" "AtmosphereLayer"
             "AtmosphereLayerBoundary" "BarrierIsland" "Beach" "Bedrock"
             "Benthic" "Benthos" "BenticEcosystem" "Biosphere" "BodyOfGround"
             "BodyOfIce" "BodyOfSeaIce" "BodyOfWater" "BorealForest"
             "BoundaryLayer" "Cave" "CaveEcosystem" "Cirque" "ClimateZoneType"
             "CoastalRegion" "Continent" "ContinentalMargin" "CoralReef" "Core"
             "CoreLayer" "CostalLandform" "Creek" "Crust" "CrustLayer"
             "Cryosphere" "CryosphereLayer" "DeepOcean" "Delta"
             "DemersalEcosystem" "DepthHoarLayer" "Desert_Ecosystem"
             "DesertClimateZone" "DryLandRegion" "Dune" "EarthRealm"
             "EcosystemType" "EolianLandform" "EstuarineWetland" "Estuary"
             "Exosphere" "F-Region" "Farmland" "FastIce" "Felsic" "fiord"
             "Fjord" "FluvialLandform" "Forest_Ecosystem" "FractureZone"
             "FreshwaterLake" "GeomorphologicalRegionType" "Geosphere"
             "GeosphereLayer" "GlacialLandform" "Glacier"
             "GlobalPlanetaryLayers" "Grassland" "GroundSurfaceLayer"
             "GroundWaterObjectBoundary" "Halocline" "Hydrosphere"
             "HydrosphereLayer" "HydrothermalVents" "Iceberg" "IceCore"
             "IceFloe" "IceLayer" "IceSheet" "Inlet" "IntertidalZone"
             "InversionLayer" "Ionosphere" "Island" "IslandArc" "Isobar"
             "Isopycnal" "KarstLandform" "LacustrineWetland" "Lagoon" "Lake"
             "LakeLayer" "Land" "Land_WaterBoundary_2D" "LandIce"
             "LandIceLayer" "LandRegion" "LandSurface" "LandSurfaceLayer"
             "LandWaterObject" "LandwaterRegion" "LandWaterSurface"
             "LandwaterSurfaceLayer" "Leads" "Lithosphere" "LithosphereLayer"
             "Litter" "Littoral" "LowerAtmosphere" "LowerMantle" "Mafic"
             "Magnetosphere" "MangroveForest" "Mantle" "MantleLayer"
             "MarineEcosystem" "MarineWetland" "Marsh"
             "MediterraneanClimateZone" "Mesopause" "Mesosphere"
             "MiddleAtmosphere" "MixedLayer" "Moho" "MontaneForest" "Mountain"
             "Nearshore" "Ocean" "OceanCrustLayer" "OceanLayer" "OceanRegion"
             "OceanRidge" "PackIce" "PalustrineWetland" "Peatland"
             "PelagicEcosystem" "PeriglacialLandform" "Permafrost"
             "PermafrostZone" "PhoticZone" "Plain" "PlanetaryStructure"
             "PlanetarySurface" "PlanetarySurfaceLayer" "PlanetEarth" "Plateau"
             "Polynya" "Pond" "Pycnocline" "RegionProperty" "Ridge"
             "RiftValley" "RiparianWetland" "River" "Rock_body" "RockGlacier"
             "RockyCoast" "SalineLake" "Savanna" "Sea" "SeaFloor"
             "SeaFloorGroundLayer" "SeaFloorRegion" "SeaFloorWaterLayer"
             "SeaIce" "SeaIceLayer" "Seamount" "SeaSurface" "SeaSurfaceLayer"
             "SedimentaryStructure" "SedimentLayer" "Shoal" "Shoreline"
             "SkinLayer" "Sky" "SnowField" "SnowLayer" "SoilLayer" "SolidEarth"
             "Spring" "Stratopause" "Stratosphere" "Stream" "SubmarineCanyon"
             "SubsurfaceWater" "SubtropicalClimateZone" "SurfaceRegion"
             "SurfaceWater" "Swamp" "Talik" "TectonicLandform"
             "TemperateClimateZone" "TerrestrialEcosystem"
             "TerrrestrialWetland" "Thermocline" "Thermosphere"
             "TopographicalRegion" "Trench" "TropicalClimateZone" "Tropopause"
             "Troposphere" "TroposphereLayer" "Tundra_Ecosystem"
             "UndergroundWater" "UpperAir" "UpperAtmosphere"
             "UpperMantle_flowing" "UpperMantle_rigid" "UrbanLand" "Volcano"
             "WaterChannel" "Watershed" "WaterSurface" "WaterSurfaceLayer"
             "WaterTable" "Wetland" "WetlandRegion"))
    (export (intern xml-query-data-model::s xml-query-data-model::p)
            xml-query-data-model::p)))

;;; (xqdm:find-namespace "http://sweet.jpl.nasa.gov/sweet/earthrealm.owl#" :if-does-not-exist :load)
