(dribble "cl-xml-0-949-20030406.txt")
(software-version)
(machine-version)
(lisp-implementation-version)
(setq *load-verbose* t)
(setq *compile-verbose* nil)
(setq *compile-print* nil)
(load "osx.tschichold:development:source:cl-xml-0-949:load-clhttp-instancenames.lisp")
;(load "/Development/Source/cl-xml-0-949/load-clhttp-instancenames.lisp")
;(load "G:\\Development\\Source\\cl-xml-0-949\\load-clhttp-instancenames.lisp")
(execute-system-operations :xtests '(:load))
(dribble)
