;;; -*- Mode: lisp; Syntax: ansi-common-lisp; Base: 10; Package: xml-query-data-model; -*-

(in-package :xml-query-data-model)
(setq xml-query-data-model:*namespace*
      (xml-query-data-model:defnamespace "http://purl.org/vocab/reuters_topics/1.0/"
                                         (:use)
                                         (:nicknames "")
                                         (:export
                                          "1POL"
                                          "2ECO"
                                          "3SPO"
                                          "4GEN"
                                          "6INS"
                                          "7RSK"
                                          "8YDB"
                                          "9BNX"
                                          "ADS10"
                                          "BNW14"
                                          "BRP11"
                                          "C11"
                                          "C12"
                                          "C13"
                                          "C14"
                                          "C15"
                                          "C151"
                                          "C1511"
                                          "C152"
                                          "C16"
                                          "C17"
                                          "C171"
                                          "C172"
                                          "C173"
                                          "C174"
                                          "C18"
                                          "C181"
                                          "C182"
                                          "C183"
                                          "C21"
                                          "C22"
                                          "C23"
                                          "C24"
                                          "C31"
                                          "C311"
                                          "C312"
                                          "C313"
                                          "C32"
                                          "C33"
                                          "C331"
                                          "C34"
                                          "C41"
                                          "C411"
                                          "C42"
                                          "CCAT"
                                          "E11"
                                          "E12"
                                          "E121"
                                          "E13"
                                          "E131"
                                          "E132"
                                          "E14"
                                          "E141"
                                          "E142"
                                          "E143"
                                          "E21"
                                          "E211"
                                          "E212"
                                          "E31"
                                          "E311"
                                          "E312"
                                          "E313"
                                          "E41"
                                          "E411"
                                          "E51"
                                          "E511"
                                          "E512"
                                          "E513"
                                          "E61"
                                          "E71"
                                          "ECAT"
                                          "ENT12"
                                          "G11"
                                          "G111"
                                          "G112"
                                          "G113"
                                          "G12"
                                          "G13"
                                          "G131"
                                          "G14"
                                          "G15"
                                          "G151"
                                          "G152"
                                          "G153"
                                          "G154"
                                          "G155"
                                          "G156"
                                          "G157"
                                          "G158"
                                          "G159"
                                          "GCAT"
                                          "GCRIM"
                                          "GDEF"
                                          "GDIP"
                                          "GDIS"
                                          "GEDU"
                                          "GENT"
                                          "GENV"
                                          "GFAS"
                                          "GHEA"
                                          "GJOB"
                                          "GMIL"
                                          "GOBIT"
                                          "GODD"
                                          "GPOL"
                                          "GPRO"
                                          "GREL"
                                          "GSCI"
                                          "GSPO"
                                          "GTOUR"
                                          "GVIO"
                                          "GVOTE"
                                          "GWEA"
                                          "GWELF"
                                          "M11"
                                          "M12"
                                          "M13"
                                          "M131"
                                          "M132"
                                          "M14"
                                          "M141"
                                          "M142"
                                          "M143"
                                          "MCAT"
                                          "MEUR"
                                          "PRB13")
                                         (:documentation nil)))

(let ((xml-query-data-model::p
       (or (find-package "http://purl.org/vocab/reuters_topics/1.0/")
           (make-package "http://purl.org/vocab/reuters_topics/1.0/"
                         :use
                         nil
                         :nicknames
                         '("")))))
  (dolist (xml-query-data-model::s
           '("1POL" "2ECO" "3SPO" "4GEN" "6INS" "7RSK" "8YDB" "9BNX" "ADS10"
             "BNW14" "BRP11" "C11" "C12" "C13" "C14" "C15" "C151" "C1511"
             "C152" "C16" "C17" "C171" "C172" "C173" "C174" "C18" "C181" "C182"
             "C183" "C21" "C22" "C23" "C24" "C31" "C311" "C312" "C313" "C32"
             "C33" "C331" "C34" "C41" "C411" "C42" "CCAT" "E11" "E12" "E121"
             "E13" "E131" "E132" "E14" "E141" "E142" "E143" "E21" "E211" "E212"
             "E31" "E311" "E312" "E313" "E41" "E411" "E51" "E511" "E512" "E513"
             "E61" "E71" "ECAT" "ENT12" "G11" "G111" "G112" "G113" "G12" "G13"
             "G131" "G14" "G15" "G151" "G152" "G153" "G154" "G155" "G156"
             "G157" "G158" "G159" "GCAT" "GCRIM" "GDEF" "GDIP" "GDIS" "GEDU"
             "GENT" "GENV" "GFAS" "GHEA" "GJOB" "GMIL" "GOBIT" "GODD" "GPOL"
             "GPRO" "GREL" "GSCI" "GSPO" "GTOUR" "GVIO" "GVOTE" "GWEA" "GWELF"
             "M11" "M12" "M13" "M131" "M132" "M14" "M141" "M142" "M143" "MCAT"
             "MEUR" "PRB13"))
    (export (intern xml-query-data-model::s xml-query-data-model::p)
            xml-query-data-model::p)))

;;; (xqdm:find-namespace "http://purl.org/vocab/reuters_topics/1.0/" :if-does-not-exist :load)
