;;; -*- Mode: lisp; Syntax: ansi-common-lisp; Base: 10; Package: xml-query-data-model; -*-

(in-package :xml-query-data-model)
(setq xml-query-data-model:*namespace*
      (xml-query-data-model:defnamespace "http://sweet.jpl.nasa.gov/ontology/biosphere.owl#"
                                         (:use)
                                         (:nicknames)
                                         (:export
                                          "Algae"
                                          "Amoebae"
                                          "Amphibian"
                                          "Anemone"
                                          "Animal"
                                          "Arachnid"
                                          "Arthropod"
                                          "Bacteria"
                                          "Bird"
                                          "BlueGreenAlgae"
                                          "Canopy"
                                          "Centipede"
                                          "Chlorophyll"
                                          "Ciliate"
                                          "Coccolithophore"
                                          "Conifer"
                                          "Coral"
                                          "Crop"
                                          "Crown"
                                          "Crustacean"
                                          "Dairy"
                                          "DeciduousVegetation"
                                          "Diatom"
                                          "DominantSpecies"
                                          "Echinoderm"
                                          "EvergreenVegetation"
                                          "ExoticSpecies"
                                          "ExoticVegetation"
                                          "Fern"
                                          "Fish"
                                          "Flagellate"
                                          "Flatworm"
                                          "FloweringPlant"
                                          "Foraminifer"
                                          "Fungi"
                                          "FungiTaxonomy"
                                          "Human"
                                          "IndigenousSpecies"
                                          "IndigenousVegetation"
                                          "Insect"
                                          "Invertebrate"
                                          "Jellyfish"
                                          "Leaf"
                                          "Lichen"
                                          "Litter"
                                          "Liverwort"
                                          "Livestock"
                                          "LivingThing"
                                          "Macroalgae"
                                          "Macrophyte"
                                          "Mammal"
                                          "MarineAnimal"
                                          "MarineBird"
                                          "MarineInvertebrate"
                                          "MarineMammal"
                                          "MarineMicrobiota"
                                          "MarinePlant"
                                          "Microalgae"
                                          "Microbiota"
                                          "MicrobiotaTaxonomy"
                                          "Microphyte"
                                          "Millipede"
                                          "Mold"
                                          "Mollusk"
                                          "Moss"
                                          "Mushroom"
                                          "Nutrient"
                                          "Phytoplankton"
                                          "Plankton"
                                          "Plant"
                                          "Pollen"
                                          "Poultry"
                                          "Protist"
                                          "Radiolarian"
                                          "Reptile"
                                          "Roundworm"
                                          "SegmentedWorm"
                                          "SlimeMold"
                                          "Sponge"
                                          "Sporozoan"
                                          "TreeRing"
                                          "Vegetation"
                                          "VegetationCover"
                                          "VegetationSpecies"
                                          "Vertebrate"
                                          "Yeast"
                                          "Zooplankton")
                                         (:documentation nil)))

(let ((xml-query-data-model::p
       (or (find-package "http://sweet.jpl.nasa.gov/ontology/biosphere.owl#")
           (make-package "http://sweet.jpl.nasa.gov/ontology/biosphere.owl#"
                         :use
                         nil
                         :nicknames
                         'nil))))
  (dolist (xml-query-data-model::s
           '("Algae" "Amoebae" "Amphibian" "Anemone" "Animal" "Arachnid"
             "Arthropod" "Bacteria" "Bird" "BlueGreenAlgae" "Canopy"
             "Centipede" "Chlorophyll" "Ciliate" "Coccolithophore" "Conifer"
             "Coral" "Crop" "Crown" "Crustacean" "Dairy" "DeciduousVegetation"
             "Diatom" "DominantSpecies" "Echinoderm" "EvergreenVegetation"
             "ExoticSpecies" "ExoticVegetation" "Fern" "Fish" "Flagellate"
             "Flatworm" "FloweringPlant" "Foraminifer" "Fungi" "FungiTaxonomy"
             "Human" "IndigenousSpecies" "IndigenousVegetation" "Insect"
             "Invertebrate" "Jellyfish" "Leaf" "Lichen" "Litter" "Liverwort"
             "Livestock" "LivingThing" "Macroalgae" "Macrophyte" "Mammal"
             "MarineAnimal" "MarineBird" "MarineInvertebrate" "MarineMammal"
             "MarineMicrobiota" "MarinePlant" "Microalgae" "Microbiota"
             "MicrobiotaTaxonomy" "Microphyte" "Millipede" "Mold" "Mollusk"
             "Moss" "Mushroom" "Nutrient" "Phytoplankton" "Plankton" "Plant"
             "Pollen" "Poultry" "Protist" "Radiolarian" "Reptile" "Roundworm"
             "SegmentedWorm" "SlimeMold" "Sponge" "Sporozoan" "TreeRing"
             "Vegetation" "VegetationCover" "VegetationSpecies" "Vertebrate"
             "Yeast" "Zooplankton"))
    (export (intern xml-query-data-model::s xml-query-data-model::p)
            xml-query-data-model::p)))

;;; (xqdm:find-namespace "http://sweet.jpl.nasa.gov/ontology/biosphere.owl#" :if-does-not-exist :load)
