;;; -*- Mode: lisp; Syntax: ansi-common-lisp; Base: 10; Package: xml-query-data-model; -*-

(in-package :xml-query-data-model)
(setq xml-query-data-model:*namespace*
      (xml-query-data-model:defnamespace "http://sweet.jpl.nasa.gov/ontology/human_activities.owl#"
                                         (:use)
                                         (:nicknames)
                                         (:export
                                          "Access"
                                          "Adult"
                                          "AerialPhotography"
                                          "Afforestation"
                                          "AgeGroup"
                                          "AgriculturalManagement"
                                          "AgriculturalProduct"
                                          "Agriculture"
                                          "Analysis"
                                          "AnatomicalParameters"
                                          "Anatomy"
                                          "AnimalBehaviorScience"
                                          "AnimalManagementSystem"
                                          "AnimalProduction"
                                          "AnimalWaste"
                                          "Anthropogenic"
                                          "Apiculture"
                                          "Aquaculture"
                                          "Bathimetry"
                                          "BehavioralScience"
                                          "BiochemicalRelease"
                                          "Biochemistry"
                                          "BiologicalHazard"
                                          "Biology"
                                          "Birth"
                                          "Breeding"
                                          "Burning"
                                          "ByProductOfHumanActivity"
                                          "Census"
                                          "CivilDisturbance"
                                          "Communications"
                                          "Conservation"
                                          "ConsumerBehavior"
                                          "Contamination"
                                          "Contours"
                                          "CroppingSystem"
                                          "CropProduct"
                                          "CropsProduction"
                                          "DairyProduct"
                                          "Death"
                                          "Desertification"
                                          "Ecology"
                                          "Ecology-RelatedActivity"
                                          "Economics"
                                          "EducationalLevel"
                                          "Electricity"
                                          "Emission"
                                          "Engineering"
                                          "EngineeringActivity"
                                          "EnvironmentalAssessment"
                                          "EquipmentCharacteristic"
                                          "Eutropication"
                                          "Expansion"
                                          "Experiment"
                                          "Fire"
                                          "Fishery"
                                          "FishProduction"
                                          "FoodScience"
                                          "ForestProduct"
                                          "FruitProduct"
                                          "GasFlaring"
                                          "Genetics"
                                          "GeologicalHazard"
                                          "Geology"
                                          "Harvesting"
                                          "Hazard"
                                          "HazardousLevel"
                                          "Hearing"
                                          "HorticulturalActivity"
                                          "HorticulturalProduct"
                                          "Human"
                                          "HumanActivity"
                                          "HumanCategory"
                                          "HumanHealth"
                                          "HydrologicalHazard"
                                          "Hydrology"
                                          "HypothesisTest"
                                          "Imaging"
                                          "IndustrialEmission"
                                          "Industrialization"
                                          "Irrigation"
                                          "KnowledgeDomain"
                                          "LandCover"
                                          "LandManagement"
                                          "LandResource"
                                          "LandscapeEcology"
                                          "LandscapeManagement"
                                          "LandTenure"
                                          "LandUse"
                                          "Leak"
                                          "Limnology"
                                          "Lithology"
                                          "LivestockProduct"
                                          "Management"
                                          "ManagementSystem"
                                          "Manure"
                                          "Mapping"
                                          "Measurement"
                                          "Meteorology"
                                          "Monitoring"
                                          "NaturalHazard"
                                          "NutritionScience"
                                          "Observation"
                                          "Oceanography"
                                          "Oceanology"
                                          "Old"
                                          "Packaging"
                                          "Paleoclimatology"
                                          "Photography"
                                          "Physiology"
                                          "PlantProduction"
                                          "PopulationDynamics"
                                          "PoultryProduct"
                                          "Preference"
                                          "Processing"
                                          "Product"
                                          "Production"
                                          "ProductivityData"
                                          "Profession"
                                          "Protection"
                                          "Psychology"
                                          "Quality"
                                          "RadiationExposure"
                                          "Reclamation"
                                          "Recreation"
                                          "Reforestation"
                                          "RemoteSensing"
                                          "Research-Exploration"
                                          "Restoration"
                                          "Revegetation"
                                          "Sampling"
                                          "Seismology"
                                          "Sense"
                                          "Sericulture"
                                          "ShellfishProduction"
                                          "Simulation"
                                          "SocialActivity"
                                          "SocialBehavior"
                                          "Sociology"
                                          "SoilCultivation"
                                          "Spill"
                                          "Storage"
                                          "Tomography"
                                          "Toxicology"
                                          "Transportation"
                                          "Urbanization"
                                          "VegetableProduct"
                                          "Vision"
                                          "VitalActivity"
                                          "VitalStatistics"
                                          "Waste"
                                          "WaterManagement"
                                          "Work"
                                          "Young")
                                         (:documentation nil)))

(let ((xml-query-data-model::p
       (or (find-package "http://sweet.jpl.nasa.gov/ontology/human_activities.owl#")
           (make-package "http://sweet.jpl.nasa.gov/ontology/human_activities.owl#"
                         :use
                         nil
                         :nicknames
                         'nil))))
  (dolist (xml-query-data-model::s
           '("Access" "Adult" "AerialPhotography" "Afforestation" "AgeGroup"
             "AgriculturalManagement" "AgriculturalProduct" "Agriculture"
             "Analysis" "AnatomicalParameters" "Anatomy"
             "AnimalBehaviorScience" "AnimalManagementSystem"
             "AnimalProduction" "AnimalWaste" "Anthropogenic" "Apiculture"
             "Aquaculture" "Bathimetry" "BehavioralScience"
             "BiochemicalRelease" "Biochemistry" "BiologicalHazard" "Biology"
             "Birth" "Breeding" "Burning" "ByProductOfHumanActivity" "Census"
             "CivilDisturbance" "Communications" "Conservation"
             "ConsumerBehavior" "Contamination" "Contours" "CroppingSystem"
             "CropProduct" "CropsProduction" "DairyProduct" "Death"
             "Desertification" "Ecology" "Ecology-RelatedActivity" "Economics"
             "EducationalLevel" "Electricity" "Emission" "Engineering"
             "EngineeringActivity" "EnvironmentalAssessment"
             "EquipmentCharacteristic" "Eutropication" "Expansion" "Experiment"
             "Fire" "Fishery" "FishProduction" "FoodScience" "ForestProduct"
             "FruitProduct" "GasFlaring" "Genetics" "GeologicalHazard"
             "Geology" "Harvesting" "Hazard" "HazardousLevel" "Hearing"
             "HorticulturalActivity" "HorticulturalProduct" "Human"
             "HumanActivity" "HumanCategory" "HumanHealth" "HydrologicalHazard"
             "Hydrology" "HypothesisTest" "Imaging" "IndustrialEmission"
             "Industrialization" "Irrigation" "KnowledgeDomain" "LandCover"
             "LandManagement" "LandResource" "LandscapeEcology"
             "LandscapeManagement" "LandTenure" "LandUse" "Leak" "Limnology"
             "Lithology" "LivestockProduct" "Management" "ManagementSystem"
             "Manure" "Mapping" "Measurement" "Meteorology" "Monitoring"
             "NaturalHazard" "NutritionScience" "Observation" "Oceanography"
             "Oceanology" "Old" "Packaging" "Paleoclimatology" "Photography"
             "Physiology" "PlantProduction" "PopulationDynamics"
             "PoultryProduct" "Preference" "Processing" "Product" "Production"
             "ProductivityData" "Profession" "Protection" "Psychology"
             "Quality" "RadiationExposure" "Reclamation" "Recreation"
             "Reforestation" "RemoteSensing" "Research-Exploration"
             "Restoration" "Revegetation" "Sampling" "Seismology" "Sense"
             "Sericulture" "ShellfishProduction" "Simulation" "SocialActivity"
             "SocialBehavior" "Sociology" "SoilCultivation" "Spill" "Storage"
             "Tomography" "Toxicology" "Transportation" "Urbanization"
             "VegetableProduct" "Vision" "VitalActivity" "VitalStatistics"
             "Waste" "WaterManagement" "Work" "Young"))
    (export (intern xml-query-data-model::s xml-query-data-model::p)
            xml-query-data-model::p)))

;;; (xqdm:find-namespace "http://sweet.jpl.nasa.gov/ontology/human_activities.owl#" :if-does-not-exist :load)
