;;; -*- Mode: lisp; Syntax: ansi-common-lisp; Base: 10; Package: xml-query-data-model; -*-

(in-package :xml-query-data-model)
(setq xml-query-data-model:*namespace*
      (xml-query-data-model:defnamespace "http://neuroscientific.net/bio-zen.owl#"
                                         (:use)
                                         (:nicknames)
                                         (:export
                                          "abstract"
                                          "abstract-quality"
                                          "alternative"
                                          "altLabel"
                                          "amino-acid-part-of-protein-population"
                                          "amount-of-matter"
                                          "arbitrary-sum"
                                          "binary-correlation"
                                          "biological-process-concept"
                                          "boundary"
                                          "broader"
                                          "broaderGeneric"
                                          "broaderInstantive"
                                          "broaderPartitive"
                                          "catalyst-modulatory-binding-concept"
                                          "catalyzed-by"
                                          "causes"
                                          "cell"
                                          "cell-concept"
                                          "cell-type-concept"
                                          "cellular-component-concept"
                                          "chem-conv-proc-type-concept"
                                          "chemical-conversion-process"
                                          "chemical-conversion-process-concept"
                                          "chemical-pathway"
                                          "compartment"
                                          "compartment-concept"
                                          "complex-assembly-process"
                                          "concentration"
                                          "Concept"
                                          "concept-from-EC-enzyme-nomenclature"
                                          "concept-from-MeSH"
                                          "concept-from-wordnet"
                                          "concluded-by"
                                          "constant-participant"
                                          "constant-value"
                                          "contains-data"
                                          "contributor"
                                          "correlates"
                                          "correlates-A"
                                          "correlates-assign"
                                          "correlates-B"
                                          "correlates-C"
                                          "correlates-D"
                                          "correlates-E"
                                          "correlates-F"
                                          "correlates-G"
                                          "correlates-H"
                                          "correlation"
                                          "correlation-concept"
                                          "coverage"
                                          "creator"
                                          "d-data"
                                          "data"
                                          "data-concept"
                                          "data-type-concept"
                                          "database-system-concept"
                                          "date"
                                          "delta-G-prime-o"
                                          "delta-H"
                                          "delta-S"
                                          "dependent-place"
                                          "derived-from"
                                          "described-by"
                                          "described-by-OR-narrower"
                                          "description"
                                          "dna-population"
                                          "download"
                                          "download-schema"
                                          "duration"
                                          "electrical-current-q"
                                          "endurant"
                                          "event"
                                          "evidence-description-concept"
                                          "exemplary-part"
                                          "experimental-modification-concept"
                                          "feature"
                                          "format"
                                          "generic-constituent"
                                          "generic-location"
                                          "genus-concept"
                                          "has-cofactor"
                                          "has-quality"
                                          "host-of"
                                          "ID"
                                          "ID-version"
                                          "identifier"
                                          "initial-value"
                                          "interestingness"
                                          "ionic-strength"
                                          "K-prime"
                                          "KEQ"
                                          "language"
                                          "life-coincidence"
                                          "luminous-intensity"
                                          "mass"
                                          "mathML"
                                          "max-deviation"
                                          "md5"
                                          "mean-molecular-mass"
                                          "meets"
                                          "mereologically-coincides"
                                          "metabolic-pathway-concept"
                                          "mime-type"
                                          "molecular-binding-concept"
                                          "molecular-binding-process"
                                          "molecular-complex-population"
                                          "molecular-function-concept"
                                          "molecular-process"
                                          "molecular-process-concept"
                                          "molecular-transport-concept"
                                          "molecular-transport-process"
                                          "molecule-OR-molecular-complex-OR-part-population"
                                          "molecule-OR-molecular-complex-population"
                                          "molecule-population"
                                          "molecule-type-concept"
                                          "narrower"
                                          "narrowerGeneric"
                                          "narrowerInstantive"
                                          "narrowerPartitive"
                                          nil
                                          nil
                                          nil
                                          nil
                                          nil
                                          nil
                                          nil
                                          nil
                                          nil
                                          nil
                                          nil
                                          nil
                                          nil
                                          nil
                                          nil
                                          nil
                                          nil
                                          "non-physical-endurant"
                                          "non-physical-object"
                                          "nucleotide-concept"
                                          "nucleotide-part-of-dna-population"
                                          "nucleotide-part-of-rna-population"
                                          "one-dimensional-quality"
                                          "organism"
                                          "organism-concept"
                                          "organismal-classification-concept"
                                          "overlaps"
                                          "part"
                                          "part-of-dna-population"
                                          "part-of-molecular-complex-population"
                                          "part-of-molecule-population"
                                          "part-of-protein-population"
                                          "part-of-rna-population"
                                          "part-of-small-molecule-population"
                                          "part-OR-participant"
                                          "participant"
                                          "participant-A"
                                          "participant-B"
                                          "particular"
                                          "partly-compresent"
                                          "perdurant"
                                          "pH"
                                          "physical-endurant"
                                          "physical-object"
                                          "physical-quality"
                                          "pMg"
                                          "precedes"
                                          "prefLabel"
                                          "process"
                                          "protein-population"
                                          "prototype"
                                          "publisher"
                                          "quality"
                                          "reaction-speed"
                                          "realness"
                                          "regards"
                                          "related"
                                          "relation"
                                          "relevant-part"
                                          "rights"
                                          "rna-population"
                                          "semanticRelation"
                                          "sequence-concept"
                                          "sequence-end-position"
                                          "sequence-length"
                                          "sequence-position"
                                          "sequence-start-position"
                                          "sibling-part"
                                          "size"
                                          "small-molecule-concept"
                                          "small-molecule-population"
                                          "solution"
                                          "source"
                                          "spatial-length"
                                          "spatial-location_q"
                                          "spatio-temporal-particular"
                                          "species-concept"
                                          "specific-constant-constituent"
                                          "started-by"
                                          "state"
                                          "stative"
                                          "status-code"
                                          "std-deviation"
                                          "stoichiometry"
                                          "strong-connection"
                                          "subject"
                                          "subsequence-part-of-dna-population"
                                          "subsequence-part-of-protein-population"
                                          "subsequence-part-of-rna-population"
                                          "temperature"
                                          "temporal-location_q"
                                          "temporal-quality"
                                          "temporal-relation"
                                          "temporally-coincides"
                                          "temporally-includes"
                                          "temporally-overlaps"
                                          "temporary-part"
                                          "tissue"
                                          "tissue-concept"
                                          "title"
                                          "transport-conversion-process"
                                          "type"
                                          "uncatalyzed-chemical-conversion-process"
                                          "url"
                                          "weak-connection")
                                         (:documentation nil)))

(let ((xml-query-data-model::p
       (or (find-package "http://neuroscientific.net/bio-zen.owl#")
           (make-package "http://neuroscientific.net/bio-zen.owl#"
                         :use
                         nil
                         :nicknames
                         'nil))))
  (dolist (xml-query-data-model::s
           '("abstract" "abstract-quality" "alternative" "altLabel"
             "amino-acid-part-of-protein-population" "amount-of-matter"
             "arbitrary-sum" "binary-correlation" "biological-process-concept"
             "boundary" "broader" "broaderGeneric" "broaderInstantive"
             "broaderPartitive" "catalyst-modulatory-binding-concept"
             "catalyzed-by" "causes" "cell" "cell-concept" "cell-type-concept"
             "cellular-component-concept" "chem-conv-proc-type-concept"
             "chemical-conversion-process"
             "chemical-conversion-process-concept" "chemical-pathway"
             "compartment" "compartment-concept" "complex-assembly-process"
             "concentration" "Concept" "concept-from-EC-enzyme-nomenclature"
             "concept-from-MeSH" "concept-from-wordnet" "concluded-by"
             "constant-participant" "constant-value" "contains-data"
             "contributor" "correlates" "correlates-A" "correlates-assign"
             "correlates-B" "correlates-C" "correlates-D" "correlates-E"
             "correlates-F" "correlates-G" "correlates-H" "correlation"
             "correlation-concept" "coverage" "creator" "d-data" "data"
             "data-concept" "data-type-concept" "database-system-concept"
             "date" "delta-G-prime-o" "delta-H" "delta-S" "dependent-place"
             "derived-from" "described-by" "described-by-OR-narrower"
             "description" "dna-population" "download" "download-schema"
             "duration" "electrical-current-q" "endurant" "event"
             "evidence-description-concept" "exemplary-part"
             "experimental-modification-concept" "feature" "format"
             "generic-constituent" "generic-location" "genus-concept"
             "has-cofactor" "has-quality" "host-of" "ID" "ID-version"
             "identifier" "initial-value" "interestingness" "ionic-strength"
             "K-prime" "KEQ" "language" "life-coincidence" "luminous-intensity"
             "mass" "mathML" "max-deviation" "md5" "mean-molecular-mass"
             "meets" "mereologically-coincides" "metabolic-pathway-concept"
             "mime-type" "molecular-binding-concept"
             "molecular-binding-process" "molecular-complex-population"
             "molecular-function-concept" "molecular-process"
             "molecular-process-concept" "molecular-transport-concept"
             "molecular-transport-process"
             "molecule-OR-molecular-complex-OR-part-population"
             "molecule-OR-molecular-complex-population" "molecule-population"
             "molecule-type-concept" "narrower" "narrowerGeneric"
             "narrowerInstantive" "narrowerPartitive" nil nil nil nil nil nil
             nil nil nil nil nil nil nil nil nil nil nil
             "non-physical-endurant" "non-physical-object" "nucleotide-concept"
             "nucleotide-part-of-dna-population"
             "nucleotide-part-of-rna-population" "one-dimensional-quality"
             "organism" "organism-concept" "organismal-classification-concept"
             "overlaps" "part" "part-of-dna-population"
             "part-of-molecular-complex-population"
             "part-of-molecule-population" "part-of-protein-population"
             "part-of-rna-population" "part-of-small-molecule-population"
             "part-OR-participant" "participant" "participant-A"
             "participant-B" "particular" "partly-compresent" "perdurant" "pH"
             "physical-endurant" "physical-object" "physical-quality" "pMg"
             "precedes" "prefLabel" "process" "protein-population" "prototype"
             "publisher" "quality" "reaction-speed" "realness" "regards"
             "related" "relation" "relevant-part" "rights" "rna-population"
             "semanticRelation" "sequence-concept" "sequence-end-position"
             "sequence-length" "sequence-position" "sequence-start-position"
             "sibling-part" "size" "small-molecule-concept"
             "small-molecule-population" "solution" "source" "spatial-length"
             "spatial-location_q" "spatio-temporal-particular"
             "species-concept" "specific-constant-constituent" "started-by"
             "state" "stative" "status-code" "std-deviation" "stoichiometry"
             "strong-connection" "subject" "subsequence-part-of-dna-population"
             "subsequence-part-of-protein-population"
             "subsequence-part-of-rna-population" "temperature"
             "temporal-location_q" "temporal-quality" "temporal-relation"
             "temporally-coincides" "temporally-includes" "temporally-overlaps"
             "temporary-part" "tissue" "tissue-concept" "title"
             "transport-conversion-process" "type"
             "uncatalyzed-chemical-conversion-process" "url"
             "weak-connection"))
    (export (intern xml-query-data-model::s xml-query-data-model::p)
            xml-query-data-model::p)))

;;; (xqdm:find-namespace "http://neuroscientific.net/bio-zen.owl#" :if-does-not-exist :load)
